config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root   'static_pages#home'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :books do
    patch 'checkout', on: :member
  end
  resources :borrowings do
    patch 'return',   on: :member
    get   'show_all', on: :collection
  end
  resources :users
  resources :roles
end

app/models/borrowing.rb
class Borrowing < ApplicationRecord
  belongs_to :book
  belongs_to :user

  scope :unreturned_books, -> { where(return_date: nil) }

  validates :book_id, presence: true
  validates :user_id, presence: true
  validates :borrowed_date, presence: true


  def Borrowing.search(text)
    if text.present?
      conditions, arguments = [], []
      terms = text.split
      terms.each do |key|
        conditions << "users.first_name ILIKE ? or users.last_name ILIKE ? or users.email ILIKE ?"
        3.times { arguments << "%#{key}%" }
      end
      joins(:user).includes(:book, :user).where([conditions.join(' or '), arguments].flatten)
    else      
      where(nil)
    end
  end

  def not_returned?
    return_date.nil?
  end

end

app/controllers/borrowings_controller.rb
class BorrowingsController < ApplicationController
  before_action :logged_in_user
  before_action :librarian, except: :index

  def index
    if current_user.student?
      @borrowings = current_user.borrowings.includes(:book).order(id: :desc).paginate(page: params[:page])
    elsif current_user.librarian?
      @borrowings = Borrowing.includes(:book, :user)
      if params.has_key?(:search) && params[:search].present?
        @borrowings = Borrowing.search(params[:search])
      end
      @borrowings = @borrowings.unreturned_books.order(id: :desc).paginate(page: params[:page])
    end
  end

  def show
    @borrowing = Borrowing.find(params[:id])
    @user = @borrowing.user
    @book = @borrowing.book
  end

  def return
    @borrowing = Borrowing.find(params[:id])
    @book = @borrowing.book
    begin
      Book.transaction do
        @book.stock.increase!
        @borrowing.update!(return_date: Time.zone.now)
      end
      flash[:success] = "The book was returned successfully."
    rescue ActiveRecord::RecordInvalid, ActiveRecord::StatementInvalid => e
      flash[:danger] = e.message
    rescue Exception => e
      flash[:danger] = e
    ensure
      redirect_to @borrowing
    end
  end

  def show_all
    @borrowings = Borrowing.includes(:book, :user)
    if params.has_key?(:search) && params[:search].present?
      @borrowings = Borrowing.search(params[:search])
    end
    @borrowings = @borrowings.order(id: :desc).paginate(page: params[:page])
    render 'index'
  end

end

app/helpers/borrowings_helper.rb
module BorrowingsHelper
end

app/views/borrowings/_borrowing.html.erb
<tr>
  <% if current_user.librarian? %>
    <td><%= borrowing.user.first_name %></td>
    <td><%= borrowing.user.last_name %></td>
    <td><%= borrowing.user.email %></td>
  <% end %>
  <td><%= link_to borrowing.book, borrowing.book %></td>
  <td><%= borrowing.borrowed_date %></td>
  <td><%= borrowing.return_date %></td>
  <td><%= link_to "Show", borrowing %></td>
</tr>

app/views/borrowings/index.html.erb
<% provide(:title, 'Borrowings') %>

<% content_for :page_header do %>
  <h1><%= yield(:title) %></h1>
<% end %>

<% if current_user.librarian? %>
  <p>
    <div class="row">
      <div class="col-md-5">
        <%= render "shared/search", url: borrowings_path, content: "Search by first name, last name and email." %>
      </div>
      <div class="col-md-7">
        <%= link_to "Show all", show_all_borrowings_path, class: "btn btn-outline-primary" %>
      </div>
    </div>
  </p>
<% end %>

<% if @borrowings.size > 0 %>
  <table class="table table-hover">
    <thead class="thead-light">
      <tr>
        <% if current_user.librarian? %>
          <th>First name</th>
          <th>Last name</th>
          <th>Email</th>
        <% end %>
        <th>Book</th>
        <th>Borrowed date</th>
        <th>Return date</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%= render @borrowings %>
    </tbody>
  </table>
  <%= will_paginate %>
<% else %>
  <h4>There are no borrowings.</h4>
<% end %>

app/views/borrowings/show.html.erb
<% provide(:title, "Borrowing ID: #{@borrowing.id}") %>

<% content_for :page_header do %>
  <h1><%= yield(:title) %></h1>
<% end %>

<dl class="row">
  <dt class="col-sm-2">Borrowed date</dt>
  <dd class="col-sm-10"><%= @borrowing.borrowed_date %></dd>
  <dt class="col-sm-2">Return date</dt>
  <dd class="col-sm-10">
    <% if current_user.librarian? && @borrowing.not_returned? %>
      <%= link_to "Return book", return_borrowing_path(@borrowing), class: "btn btn-primary", method: :patch, data: { confirm: "Are you sure?" } %>
    <% end %>
    <%= @borrowing.return_date %>
  </dd>
</dl>

<div class="row">
  <div class="col-sm">
    <div class="card">
      <h5 class="card-header">User</h5>
      <div class="card-body">
        <p class="card-text">
          <dl class="row">
            <dt class="col-sm-4">First name</dt>
            <dd class="col-sm-8"><%= @user.first_name %></dd>
            <dt class="col-sm-4">Last Name</dt>
            <dd class="col-sm-8"><%= @user.last_name %></dd>
            <dt class="col-sm-4">Email</dt>
            <dd class="col-sm-8"><%= @user.email %></dd>
          </dl>
        </p>
      </div>
    </div>
  </div>
  <div class="col-sm">
    <div class="card">
      <h5 class="card-header">Book</h5>
      <div class="card-body">
        <p class="card-text">
          <dl class="row">
            <dt class="col-sm-4">Title</dt>
            <dd class="col-sm-8"><%= @book.title %></dd>
            <dt class="col-sm-4">Author</dt>
            <dd class="col-sm-8"><%= @book.author %></dd>
            <dt class="col-sm-4">Published year</dt>
            <dd class="col-sm-8"><%= @book.published_year %></dd>
            <dt class="col-sm-4">Genre</dt>
            <dd class="col-sm-8"><%= @book.genre %></dd>
            <dt class="col-sm-4">Copies</dt>
            <dd class="col-sm-8"><%= number_with_delimiter(@book.copies) %></dd>
          </dl>
        </p>
      </div>
    </div>
  </div>
</div>

<%= link_to "Go to borrowings page", borrowings_path, class: "btn btn-link" %>