config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root   'static_pages#home'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :books do
    patch 'checkout', on: :member
  end
  resources :borrowings do
    patch 'return',   on: :member
    get   'show_all', on: :collection
  end
  resources :users
  resources :roles
end

app/models/book.rb
class Book < ApplicationRecord

  has_one   :stock
  has_many  :borrowings

  validates :title, presence: true
  validates :author, presence: true
  validates :published_year, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :genre, presence: true
  validates :copies, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def to_s
    title
  end

  def Book.search(text)    
    if text.present?
      conditions, arguments = [], []
      terms = text.split
      terms.each do |key|
        conditions << "title ILIKE ? or author ILIKE ? or genre ILIKE ?"
        3.times { arguments << "%#{key}%" }
      end
      where([conditions.join(' or '), arguments].flatten)
    else      
      where(nil)
    end
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :logged_in_user
  before_action :librarian, only: [:new, :create, :edit, :update]
  before_action :student, only: [:checkout]

  def index
    @books = Book.order(title: :asc)
    if params.has_key?(:search) && params[:search].present?
      @books = Book.search(params[:search])
    end
    @books = @books.paginate(page: params[:page])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      @book.create_stock!(quantity: @book.copies)
      flash[:success] = "Book created successfully."
      redirect_to @book
    else
      render 'new'
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:success] = "Book updated successfully."
      redirect_to @book
    else
      render 'edit'
    end
  end

  def checkout
    @book = Book.find(params[:id])
    if @book.stock.available?
      @borrowing = @book.borrowings.build(user: current_user, borrowed_date: Time.zone.now)
      begin
        Book.transaction do
          @book.stock.decrease!
          @borrowing.save!
        end
        flash[:success] = "The book was check out successfully."
      rescue ActiveRecord::RecordInvalid, ActiveRecord::StatementInvalid => e
        flash[:danger] = e.message
      rescue Exception => e
        flash[:danger] = e
      ensure
        redirect_to @book
      end
    else
      flash[:danger] = "The book was not checked out. Available copies: #{@book.stock.quantity}"
      redirect_to @book
    end
  end

  private

    def book_params
      params.require(:book).permit(:title, :author, :published_year, :genre, :copies)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<tr>
  <td><%= link_to book.title, book %></td>
  <td><%= book.author %></td>
  <td class="text-center"><%= book.published_year %></td>
  <td><%= book.genre %></td>
</tr>

app/views/books/_form.html.erb
<div class="row">
  <div class="col-md-8 offset-md-2">
    <%= form_with model: @book, local: true do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class='form-group required'>
        <%= f.label :title, class: 'control-label' %>
        <%= f.text_field :title, class: 'form-control', required: true, autofocus: true %>
        <small id="title_help" class="form-text text-black-50">Enter the book's title.</small>
      </div>
      <div class='form-group required'>
        <%= f.label :author, class: 'control-label' %>
        <%= f.text_field :author, class: 'form-control', required: true %>
        <small id="author_help" class="form-text text-black-50">Enter the book's author.</small>
      </div>
      <div class='form-group required'>
        <%= f.label :published_year, class: 'control-label' %>
        <%= f.number_field :published_year, class: 'form-control', required: true %>
        <small id="published_year_help" class="form-text text-black-50">Enter the book's published year.</small>
      </div>
      <div class='form-group required'>
        <%= f.label :genre, class: 'control-label' %>
        <%= f.text_field :genre, class: 'form-control', required: true %>
        <small id="genre_help" class="form-text text-black-50">Enter the book's genre.</small>
      </div>
      <% if f.object.new_record? %>
        <div class='form-group required'>
          <%= f.label :copies, class: 'control-label' %>
          <%= f.number_field :copies, class: 'form-control', required: true %>
          <small id="copies_help" class="form-text text-black-50">Enter the quantity of available copies of the book.</small>
        </div>
      <% end %>
      <%= f.submit nil, class: "btn btn-primary", data: { disable_with: "Processing..." } %>
      <%= link_to 'Cancel', books_path, class: "btn btn-secondary" %>
    <% end %>
  </div>
</div>

app/views/books/edit.html.erb
<% provide(:title, 'Edit book') %>

<% content_for :page_header do %>
  <%= yield(:title) %>
<% end %>

<%= render "form" %>

app/views/books/index.html.erb
<% provide(:title, 'Books') %>

<% content_for :page_header do %>
  <h1><%= yield(:title) %></h1>
<% end %>

<p>
  <div class="row">
    <div class="col-md-5">
      <%= render "shared/search", url: books_path, content: "Search title, autor or genre." %>
    </div>
  </div>
</p>

<% if current_user.librarian? %>
  <p>
    <%= link_to "New book", new_book_path, class: "btn btn-primary" %>
  </p>
<% end %>

<% if @books.size > 0 %>
  <table class="table">
    <thead class="thead-light">
      <tr>
        <th>Title</th>
        <th>Author</th>
        <th class="text-center">Published year</th>
        <th>Genre</th>
      </tr>
    </thead>
    <tbody>
      <%= render @books %>
    </tbody>
  </table>
  <%= will_paginate %>
<% else %>
  <h4>There are no books.</h4>
<% end %>

app/views/books/new.html.erb
<% provide(:title, 'Add new book') %>

<% content_for :page_header do %>
  <%= yield(:title) %>
<% end %>

<%= render "form" %>

app/views/books/show.html.erb
<% provide(:title, "Book: #{@book}") %>

<% content_for :page_header do %>
  <h1><%= yield(:title) %></h1>
<% end %>

<div class="row">
  <div class="col-sm-9">
    <dl class="row">
      <dt class="col-sm-3">Title</dt>
      <dd class="col-sm-9"><%= @book.title %></dd>
      <dt class="col-sm-3">Author</dt>
      <dd class="col-sm-9"><%= @book.author %></dd>
      <dt class="col-sm-3">Published year</dt>
      <dd class="col-sm-9"><%= @book.published_year %></dd>
      <dt class="col-sm-3">Genre</dt>
      <dd class="col-sm-9"><%= @book.genre %></dd>
      <% if current_user.librarian? %>
        <dt class="col-sm-3">Copies</dt>
        <dd class="col-sm-9"><%= number_with_delimiter(@book.copies) %></dd>
      <% end %>
    </dl>
  </div>
  <div class="col-sm-3">
    <div class="card">
      <h5 class="card-header">Available copies</h5>
      <div class="card-body">
        <h3 class="card-title">Quantity <span class="badge badge-secondary"><%= @book.stock.present? ? number_with_delimiter(@book.stock.quantity) : 0 %></span></h3>
        <% if current_user.student? && @book.stock.present? %>
          <% if @book.stock.available? %>
            <%= link_to "Check out!", checkout_book_path(@book), class: "btn btn-primary", method: :patch, data: { confirm: "Are you sure?" } %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<% if current_user.librarian? %>
  <%= link_to "Edit book", edit_book_path(@book), class: "btn btn-secondary" %>
<% end %>

<%= link_to "Go to books page", books_path, class: "btn btn-link" %>