config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root   'static_pages#home'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :books do
    patch 'checkout', on: :member
  end
  resources :borrowings do
    patch 'return',   on: :member
    get   'show_all', on: :collection
  end
  resources :users
  resources :roles
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <div class="container-fluid">
    <%= link_to "My U Library", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <% if logged_in? %>
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <%= link_to "Books", books_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Borrowings", borrowings_path, class: "nav-link" %>
          </li>
          <% if current_user.librarian? %>
            <li class="nav-item">
              <%= link_to "Users", users_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Roles", roles_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_user.first_name %>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "My profile", current_user, class: "dropdown-item" %>
              <%= link_to "Settings", edit_user_path(current_user), class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to "Log out", logout_path, method: "delete", class: "dropdown-item" %>
            </div>
          </li>
        </ul>
      <% end %>
      <% unless logged_in? %>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to "Log in", login_path, class: "nav-link" %>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My U Library | <%= yield(:title) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'layouts/header' %>

    <main class='container'>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %> alert-dismissible fade show" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= message.html_safe %>
        </div>
      <% end %>

      <% if content_for?(:page_header) %>
        <div class="pb-2 mt-4 mb-2 border-bottom">
          <h1><%= yield(:page_header) %></h1>
        </div>
      <% end %>

      <%= yield %>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>